env:
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  no-console:
    - error
    - allow:
      - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
